name: "Validate dependencies"
description: "Validate dependencies"
runs:
  using: "composite"
  steps:
      - name: Check dependencies
        run: yarn audit --groups "dependencies" --level high
        shell: bash